version: '3'
services:
  dockit:
    build: .
    volumes:
      - ./ligands/PDB:/ligands/PDB
      - ./targets/PDB:/targets/PDB
      - ./ligands/PDBQT:/ligands/PDBQT
      - ./targets/PDBQT:/targets/PDBQT
      - ./dockit_param.csv:/dockit_param.csv
      - ./results:/results
      - ./error.log:/error.log
      - ./info.log:/info.log
    environment:
      - PYTHONUNBUFFERED=1
