version: '3'
services:
  dockit:
    build: .
    volumes:
      - ./ligands/PDB:/ligands/PDB
      - ./targets/PDB:/targets/PDB
      - ./dockit_param.csv:/dockit_param.csv
      - ./results:/results
      - ./app/dockit.logs:/app/dockit.logs
