name: dockit
channels:
  - conda-forge
  - insilichem
  - bioconda
  - defaults
dependencies:
  - autodock-vina=1.1.2
  - autodocktools-prepare=1.5.7
  - openbabel=3.0.0
  - python=2.7.17
  - qvina=2.1.0
  - smina=2017.11.9



